version: '3.7'
services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    links:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD=password
    depends_on:
      - db
  office:
    image: collabora/code
    restart: always
    ports:
      - 9980:9980
    cap_add:
      - MKNOD
    environment:
      - extra_params=--o:ssl.enable=false
