version: '3.7'

#volumes:
#  nextcloud: www
#  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=41204120
      - MYSQL_PASSWORD=4120
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - production

#  office:
#    image: collabora/code
#    restart: always
#    ports:
#       - 9980:9980
#    environment:
#       - domain=172.16.0.3:8080
#    cap_add:
#       - MKNOD
#    depends_on:
#       - "app"

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    environment:
     - MYSQL_HOST=db
     - MYSQL_DATABASE=nextcloud
     - MYSQL_USER=nextcloud
     - MYSQL_PASSWORD=4120
     - NEXTCLOUD_ADMIN_USER=administrador
     - NEXTCLOUD_ADMIN_PASSWORD=41204120
    volumes:
      - ./www:/var/www/html
    restart: always
    depends_on:
      - "db"
    networks:
      - production

networks:
  production:
    driver: bridge
